kvmtool: Makefile: fix lkvm-static compiling errors
This is regression issue introduced by patch:
0001-tools-kvm-fix-assumption-of-no-IP-options.patch

This line of code breaks SOURCE_AIO try-build logic
CFLAGS  += $(WARNINGS) -DCONFIG_HAS_AIO

The compiling error:
 # make lkvm-static
disk/core.static.o: In function `disk_image__thread':
kvmtool/disk/core.c:69: undefined reference to `io_getevents'
disk/core.static.o: In function `disk_image__new':
kvmtool/disk/core.c:112: undefined reference to `io_setup'
util/read-write.static.o: In function `aio_pwritev':
kvmtool/util/read-write.c:332: undefined reference to `io_submit'
util/read-write.static.o: In function `aio_preadv':
kvmtool/util/read-write.c:349: undefined reference to `io_submit'
collect2: error: ld returned 1 exit status
make: *** [lkvm-static] Error 1

Signed-off-by: Xiaochen Shen <xiaochen.shen@intel.com>
Signed-off-by: Dimitri John Ledkov <dimitri.j.ledkov@intel.com>